apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure
  name: dev-ro-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments", "replicasets", "services"]
  verbs: ["get", "watch", "list"]
