apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: super-user
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["deployments", "pods"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
