apiVersion: v1
kind: Pod
metadata:
  name: high-priority
  namespace: rq-demo
spec:
  containers:
  - name: high-priority
    image: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
